apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jane-rb
  namespace: dev
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: admin
subjects:
- kind: ServiceAccount
  apiGroup: ""
  name: jane
#  namespace: dev