apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ken-rb
  namespace: dev
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
- kind: ServiceAccount
  apiGroup: ""
  name: ken
#  namespace: dev