apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carol-crb
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: custom-cluster-role
subjects:
- kind: ServiceAccount
  apiGroup: ""
  name: *
  namespace: prometheus
