apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: carol-rb
  namespace: prometheus
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: custom-role
subjects:
- kind: ServiceAccount
  apiGroup: ""
  name: carol-sa
  namespace: prometheus
