apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-proxy
  namespace: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: custom-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  name: carol-sa
  namespace: prometheus
