# From v1.24 k8s will no longer generate token for SA automatically after its creation.
# So you have to create Secret with annotations for the specified ServiceAccount and then k8s will fill
# the secret with token value after its creation.
apiVersion: v1
kind: Secret
metadata:
  name: bob-sa-token
  annotations:
    kubernetes.io/service-account.name: bob-sa
type: kubernetes.io/service-account-token
