parameters:
  name: cartservice
  namespace: hipster-shop
  ports:
    name: grpc
    port: 7070
  image: gcr.io/google-samples/microservices-demo/cartservice:v0.1.3
  replicas: 1
  kapitan:
    mains:
      - components/cartservice/main.jsonnet