apiVersion: monitoring.coreos.com/v1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config-main
  namespace: monitoring
spec:
  route:
    group_by: ['alertname']
    receiver: 'email-notifications'
  receivers:
  - name: 'email-notifications'
    email_configs:
    - to: 'alerts@example.com'
