apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-pod-monitor
  labels:
    app: nginx
spec:
  podMetricsEndpoints:
    - port: exporter-port
      path: /metrics
  selector:
    matchLabels:
      app: nginx
  # namespaceSelector:
  #   matchNames:
  #     - your-namespace
