apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework # имя CRD должно иметь формат plural.group
spec:
  scope: Namespaced     # Данный CRD будер работать в рамках namespace
  group: otus.homework  # Группа, отражается в поле apiVersion CR
  versions:             # Список версий
    - name: v1
      served: true      # Будет ли обслуживаться API-сервером данная версия
      storage: true     # Фиксирует  версию описания, которая будет сохраняться в etcd
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                message:
                  type: string
            spec:
              type: object
              properties:
                image: 
                  type: string
                database:
                  type: string
                password:
                  type: string
                storage_size:
                  type: string
                  pattern: "^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$"
              required:
              - image
              - database
              - password
              - storage_size
      additionalPrinterColumns:
      - name: Size
        type: string
        jsonPath: .spec.storage_size
      - name: Message
        type: string
        jsonPath: .status.message
      subresources:
        status: {}            
  names:                # различные форматы имени объекта CR
    kind: MySQL         # kind CR
    plural: mysqls      
    singular: mysql
    shortNames:
      - ms
    categories:
      - all