kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mysql-operator-crb
subjects:
- kind: ServiceAccount
  name: mysql-operator-sa
roleRef:
  kind: ClusterRole
  name: mysql-operator-cr
  apiGroup: rbac.authorization.k8s.io