apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: Metadata
    verbs: ["create"]
    resources:
    - group: "apps"
      resources: ["deployments"]
  - level: RequestResponse
    verbs: ["get"]
    resources:
    - group: "apps"
      resources: ["deployments"]