apiVersion: v1
kind: Pod
metadata:
  name: testing-alpine
  namespace: default
spec:
  containers:
  - name: testing-alpine
    image: alpine
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
